export type UserErrorCodes =
  | 'USER_NAME_ERROR'
  | 'USER_NAME_LENGTH_ERROR'
  | 'USER_PASSWORD_LENGTH_ERROR'
  | 'USER_PASSWORD_NUMBER_REQUIRED_ERROR'
  | 'USER_PASSWORD_SPECIAL_CHARACTER_REQUIRED_ERROR'
  | 'INVALID_USER_PASSWORD_UPPERCASE_REQUIRED_ERROR'
  | 'USER_USERNAME_HYPHENS_LETTERS_ONLY_ERROR'
  | 'USER_USERNAME_LENGTH_ERROR'
  | 'USER_USERNAME_NO_LEADING_HYPHEN_ERROR'
  | 'USER_USERNAME_NO_TRAILING_HYPHEN_ERROR';
