export type UserErrorCodes =
  | 'INVALID_USER_NAME'
  | 'INVALID_USER_NAME_LENGTH'
  | 'INVALID_USER_PASSWORD_LENGTH'
  | 'INVALID_USER_PASSWORD_NUMBER_REQUIRED'
  | 'INVALID_USER_PASSWORD_SPECIAL_CHARACTER_REQUIRED'
  | 'INVALID_USER_PASSWORD_UPPERCASE_REQUIRED'
  | 'INVALID_USER_USERNAME_HYPHENS_LETTERS_ONLY'
  | 'INVALID_USER_USERNAME_LENGTH'
  | 'INVALID_USER_USERNAME_NO_LEADING_HYPHEN'
  | 'INVALID_USER_USERNAME_NO_TRAILING_HYPHEN';
