export type UserErrorCode =
  | 'INVALID_USER_METHOD_NOT_IMPLEMENTED_YET'
  | 'INVALID_USER_NAME'
  | 'INVALID_USER_NAME_LENGTH'
  | 'INVALID_USER_PASSWORD'
  | 'INVALID_USER_PASSWORD_LENGTH'
  | 'INVALID_USER_USERNAME'
  | 'INVALID_USER_USERNAME_LENGTH';
